### PR TITLE
Add Go, Java, Rust, Ruby, Swift, and Kotlin extensions to code-testing-extensions

### PR DESCRIPTION
**Pull request by Evangelink**
Adds six new language-specific guidance files to the `code-testing-extensions` skill so the code-testing pipeline has curated guidance for more ecosystems.

## What changed

New extension files under `plugins/dotnet-test/skills/code-testing-extensions/extensions/`:

| File | Coverage |
|---|---|
| `go.md` | `go test`, table-driven tests, package layout (`package foo` vs `foo_test`), build tags, mocking via interfaces |
| `java.md` | Maven & Gradle (with wrappers), JUnit 4/5 + TestNG detection, Mockito (incl. final-class gotchas), Spring Boot slices |
| `rust.md` | `cargo test`/`cargo check`, unit/integration/doc tests, features, async harnesses, workspace targeting |
| `ruby.md` | RSpec & Minitest, Bundler, Rails specifics (Zeitwerk, slice tests), MockK/Mocha, factories |
| `swift.md` | SPM and Xcode (`swift test`, `xcodebuild test`), XCTest vs Swift Testing, `@testable import`, async/throws tests |
| `kotlin.md` | Gradle (incl. KMP source sets), JUnit/Kotest detection, MockK + coroutines test, Android (Robolectric vs instrumented) |

Each follows the same template as the existing `python.md` / `typescript.md` files:

- "Investigate the Repo First" rule
- Toolchain / build-tool detection
- Build, test, and lint commands
- Project layout & imports
- Test file naming and templates
- Common errors with fixes
- Mocking rules
- Dependency installation as last resort
- "Skip Coverage Tools" footer

`SKILL.md` is updated to advertise the new files in the discovery table.

## Out of scope

Per request, the existing `cpp.md` stub is left as-is rather than expanded.

## Validation

`skill-validator check --plugin plugins/dotnet-test` passes:

> All checks passed (22 skill(s), 11 agent(s), 1 plugin(s))

The two warnings on the `code-testing-extensions` discovery `SKILL.md` ("no code blocks", "no numbered workflow steps") are pre-existing and by design - the file is just a routing index of paths.

### CODE REVIEW

**Comment by Evangelink** [comment]
@copilot address review comments and fix markdown lint issues

File: plugins/dotnet-test/skills/code-testing-extensions/extensions/kotlin.md [hunk 1]
```diff
@@ -0,0 +1,226 @@
...
+    assertEquals(LoadState.Done, sut.state.value)
+}
+```
+
+## Common Errors
+
+| Error | Fix |
+|-------|-----|
+| `Unresolved reference: X` | Add the import; verify the test source set sees the production source set; for KMP, the dep may be declared only in `jvmTest` |
+| `Cannot access 'X': it is internal in module Y` | Either move the test into the same Gradle module, or mark the symbol `@VisibleForTesting internal` deliberately |
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply plugins/dotnet-test/skills/code-testing-extensions/extensions/kotlin.md]: Fixed in c693c07: corrected the fix. `@VisibleForTesting` does not widen Kotlin visibility, so the guidance now directs agents to move the test into the same module, expose a public testing seam (e.g. a `*-testing` artifact), or use `-Xfriend-paths` rather than relying on the annotation.

File: plugins/dotnet-test/skills/code-testing-extensions/extensions/java.md [hunk 2]
```diff
@@ -0,0 +1,198 @@
...
+| Layout | Test placement |
+|--------|----------------|
+| Standard | `src/test/java/<same package as production class>/<ClassName>Test.java` |
+| Integration tests separated | `src/integrationTest/java/...` (Gradle) or `src/it/java/...` (Maven w/ failsafe) |
+| Multi-module Maven | Tests live in the same module as the code under test |
+
+- Test classes must mirror the production class's **package** to access package-private members
+- Use **wildcard imports** only if the repo already does — most style guides discourage them
+- For JUnit 5: `import org.junit.jupiter.api.*;` and `import static org.junit.jupiter.api.Assertions.*;`
+- For JUnit 4: `import org.junit.*;` and `import static org.junit.Assert.*;`
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply plugins/dotnet-test/skills/code-testing-extensions/extensions/java.md]: Fixed in c693c07: rephrased the bullets to avoid the wildcard-import contradiction. They now point at the explicit imports shown in the templates below instead of recommending `.*` imports.

File: plugins/dotnet-test/skills/code-testing-extensions/extensions/java.md [hunk 3]
```diff
@@ -0,0 +1,198 @@
...
+| `No tests found for given includes` (Gradle) | `--tests` pattern doesn't match; class must be public, methods annotated with `@Test`, and class name matches the test task's `include` pattern (default `**/*Test*.class`) |
+| `Test class should have exactly one public zero-argument constructor` (JUnit 4) | Remove constructors with parameters; use `@Before` for setup |
+| `org.junit.runners.model.InvalidTestClassError` (JUnit 4) | Class is missing `public`, has wrong constructor, or method signature is wrong |
+| Mixing `org.junit.Test` (4) and `org.junit.jupiter.api.Test` (5) | Pick one framework per test class — imports must match the framework annotation |
+| `java.lang.NoClassDefFoundError` at runtime | Test runtime classpath is missing a transitive dep; add it to `testRuntimeOnly` (Gradle) or `<scope>test</scope>` (Maven) |
+| `UnsupportedClassVersionError` | JDK used to run tests is older than the JDK used to compile; align toolchains |
+| `Mockito cannot mock final class` | Add `mockito-inline` dep (or `mockito-subclass` in Mockito 5+), or refactor the class to be non-final |
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply plugins/dotnet-test/skills/code-testing-extensions/extensions/java.md]: Fixed in c693c07: replaced the incorrect `mockito-subclass` suggestion with Mockito's inline mock maker (default in Mockito 5+, `mockito-inline` artifact for 3.x/4.x), and noted MockK as the Kotlin alternative.

File: plugins/dotnet-test/skills/code-testing-extensions/extensions/kotlin.md [hunk 4]
```diff
@@ -0,0 +1,226 @@
...
+| `Mockito cannot mock final class` | Kotlin classes are `final` by default — either use **MockK** (works with final classes) or apply the `kotlin-allopen` plugin scoped to a marker annotation |
+| `MissingMockKException` | The mock wasn't initialized; call `MockKAnnotations.init(this)` or use `@MockK` with `@MockKExtension` (JUnit 5) |
+| KMP common test references a JVM-only API | Move the test to `jvmTest`, or use `expect/actual` declarations |
+| Android: `Method ... not mocked` | The unit test runs on the JVM and the SDK class is just a stub — either use Robolectric, move the test to instrumented (`androidTest`), or refactor to inject the dependency |
+
+## Mocking Rules
+
+- **MockK** is the de-facto standard for Kotlin (final classes, coroutine support): `every { mock.foo() } returns 1`, `coEvery { mock.suspendFn() } returns 1`, `verify { mock.foo() }`, `coVerify { ... }`
+- Mockito works on Kotlin too with `mockito-kotlin` extensions, but you'll need `mockito-inline`/`mockito-subclass` for final classes
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply plugins/dotnet-test/skills/code-testing-extensions/extensions/kotlin.md]: Fixed in c693c07: same correction as the Java one — Mockito's inline mock maker handles final classes (default in Mockito 5+, `mockito-inline` artifact for 3.x/4.x). Removed the incorrect `mockito-subclass` suggestion.

File: plugins/dotnet-test/skills/code-testing-extensions/extensions/kotlin.md [hunk 5]
```diff
@@ -0,0 +1,226 @@
...
+- Add `org.jetbrains.kotlinx:kotlinx-coroutines-test` only if it's already on the classpath
+- Use `runTest { ... }` (replaces the older `runBlockingTest`) for `suspend` test bodies
+- For virtual time advance, get the dispatcher from `testScheduler` rather than calling `delay` and waiting in real time
+- Inject a `CoroutineDispatcher` into production code instead of using `Dispatchers.Main/IO` directly — then swap it in tests via `Dispatchers.setMain(testDispatcher)`
+
+```kotlin
+@Test
+fun `loads data eventually`() = runTest {
+    val repo = FakeRepo()
+    val sut = Loader(repo, testScheduler.testDispatcher())
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply plugins/dotnet-test/skills/code-testing-extensions/extensions/kotlin.md]: Fixed in c693c07: replaced `testScheduler.testDispatcher()` with `StandardTestDispatcher(testScheduler)` (also mentioned `UnconfinedTestDispatcher` as an option), and updated the example accordingly.

File: plugins/dotnet-test/skills/code-testing-extensions/extensions/kotlin.md [hunk 6]
```diff
@@ -0,0 +1,226 @@
...
+
+    "divide by zero throws" {
+        shouldThrow<ArithmeticException> { Calculator().divide(1, 0) }
+    }
+})
+```
+
+## Coroutines
+
+- Add `org.jetbrains.kotlinx:kotlinx-coroutines-test` only if it's already on the classpath
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply plugins/dotnet-test/skills/code-testing-extensions/extensions/kotlin.md]: Fixed in c693c07: rephrased to 'use it when already on the classpath; otherwise add it as `testImplementation` only after confirming it is missing (see Dependency Installation).'

File: plugins/dotnet-test/skills/code-testing-extensions/extensions/ruby.md [hunk 7]
```diff
@@ -0,0 +1,191 @@
...
+| By name | `bundle exec rspec -e "creates a widget"` |
+| Tagged | `bundle exec rspec --tag focus` |
+| Fail fast | `bundle exec rspec --fail-fast` |
+| Documentation format | `bundle exec rspec --format documentation` |
+
+### Minitest
+
+| Scope | Command |
+|-------|---------|
+| All tests | `bundle exec rake test` (Rails) or `bundle exec ruby -Ilib -Itest -e 'Dir.glob("./test/**/*_test.rb").each { require _1 }'` |
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply plugins/dotnet-test/skills/code-testing-extensions/extensions/ruby.md]: Fixed in c693c07: replaced `_1` with an explicit block parameter `{ |f| require f }` so the command works on Ruby versions earlier than 2.7.

File: plugins/dotnet-test/skills/code-testing-extensions/extensions/java.md [hunk 8]
```diff
@@ -0,0 +1,198 @@
...
+}
+```
+
+## Common Errors
+
+| Error | Fix |
+|-------|-----|
+| `package X does not exist` | Add the dependency to `pom.xml` / `build.gradle`; run `./mvnw dependency:resolve` or `./gradlew --refresh-dependencies` |
+| `cannot find symbol` | Verify class name and import path; check that the test source set sees the production source set |
+| `No tests found for given includes` (Gradle) | `--tests` pattern doesn't match; class must be public, methods annotated with `@Test`, and class name matches the test task's `include` pattern (default `**/*Test*.class`) |
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply plugins/dotnet-test/skills/code-testing-extensions/extensions/java.md]: Fixed in c693c07: scoped the 'class must be public' requirement to JUnit 4 only, since JUnit Jupiter allows package-private test classes and methods (matching the template above).

File: plugins/dotnet-test/skills/code-testing-extensions/extensions/swift.md [hunk 9]
```diff
@@ -0,0 +1,227 @@
...
+
+## Common Errors
+
+| Error | Fix |
+|-------|-----|
+| `cannot find 'X' in scope` from a test | Add `@testable import MyLibrary` (and ensure the test target depends on it) |
+| `module 'MyLibrary' was not compiled for testing` | Build the production target with `-enable-testing`; SPM test targets do this automatically — Xcode Debug configs need "Enable Testability" = YES |
+| `failed to launch test runner` (Xcode) | Simulator destination may be invalid; list with `xcrun simctl list devices` and pick an existing one |
+| `No such module 'XCTest'` outside a test target | XCTest is only available in test targets — do not import it from production code |
+| `Static method 'expect(_:_:sourceLocation:)' is unavailable` | Swift Testing requires Xcode 16 / Swift 5.10+; either upgrade or use XCTest |
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply plugins/dotnet-test/skills/code-testing-extensions/extensions/swift.md]: Fixed in c693c07: corrected to require Swift 6 / Xcode 16+, with a fallback to XCTest on older toolchains. Also added `No such module 'Testing'` as a related error symptom.

**Review by JanKrivanek — APPROVED** [review]
